### PR TITLE
Fixed httpexception add dynamic form builder

### LINKED ISSUE #69: No 302 redirect after form save
Issue with sulu handling 302 under staging and production rendering the default exception template. The browser will not set the headers correctly.

### PR DESCRIPTION
**Pull request by alexander-schranz**
fixes #69

### CODE REVIEW

File: Form/Builder.php [hunk 1]
```diff
@@ -0,0 +1,319 @@
...
+            $locale,
+            $formEntity,
+            $webspaceKey,
+            $defaults
+        );
+
+        // Handle request
+        $form->handleRequest($request);
+
+        return [$formType, $form];
```
Comment (wachterjohannes) [inline Form/Builder.php:198]: cannt we get the form-type from the form? (getter)

File: Form/Builder.php [hunk 2]
```diff
@@ -0,0 +1,319 @@
...
+     * @param string $typeId
+     * @param string $typeName
+     * @param string $locale
+     * @param string $name
+     *
+     * @return string
+     */
+    protected function getKey($id, $type, $typeId, $typeName, $locale, $name)
+    {
+        // TODO
```
Comment (wachterjohannes) [inline Form/Builder.php]: ???

**Review by wachterjohannes — CHANGES_REQUESTED** [review]

File: Form/Builder.php (hunk 1 above)
Comment (alexander-schranz) [reply Form/Builder.php:198]: Did debug through the form but didnt found any any formType in it.

Comment (wachterjohannes) [reply Form/Builder.php:198]: i dont like the return array thing ... but ok we should give it a try and make it better when port it to sulu form-bundle

Comment (alexander-schranz) [reply Form/Builder.php:198]: type currently stores the data for email which currently is needed before the form is submitted.
In the refractoring for sulu form bundle the `AbstractType` need to be removed (https://github.com/sulu/SuluFormBundle/issues/8). It can get the needed information directly from `$dynamic->getForm()->...` or from a configuration.

File: Form/Builder.php (hunk 2 above)
Comment (alexander-schranz) [reply Form/Builder.php]: @wachterjohannes added implementation see last commit: https://github.com/alexander-schranz/sulu-form-bundle/pull/111/commits/fc1eb07c374c27052dfc836b4bb489a600a4e8c8

**Review by wachterjohannes — APPROVED** [review]
